### ISSUE TITLE
Naamgeving en begrijpelijkheid - custom properties

### ISSUE THREAD

**Issue by saschavanvliet** [Kitkatisvibing/look-and-feel-styleguide#10]
Jullie hebben een hele uitgebreide body met veel inhoud. Soms zijn jullie namen bij sommige custom properties wel erg lang. Misschien is het een goed idee om ze iets beknopter op te schrijven. 

```
/* input type radio when checked */
  --background-color-radio-input-checked: #444B75;
  --border-color-radio-input-checked: #444B75;
```
Groetjes, Team Drop&Heal

**Comment by Ravirkt** [comment]
bedankt voor de feedback

We hadden expres langere benamingen gebruikt zodat het voor ieder teamlid duidelijk zou zijn.

groetjes, team tumi mundo
