### ISSUE TITLE
volledigheid stylesheet ( nav)

### ISSUE THREAD

**Issue by Nayomekaia** [Kitkatisvibing/look-and-feel-styleguide#11]
In jullie css ontbreekt de nav styling, dit kan komen omdat jullie misschien geen nav hebben alleen is het niet duidelijk omdat deze wel in jullie stylesheet website staat. Dus deze kunnen jullie  toevoegen of anders weghalen uit de stylesheet website. 
<img width="765" alt="Scherm­afbeelding 2024-11-15 om 10 58 08" src="https://github.com/user-attachments/assets/32f119d8-ea3f-4a18-816c-7a464eecb58b">

**Comment by Ravirkt** [comment]
bedankt voor de feedback

We hebben de feedback geimplementeerd.
