### ISSUE TITLE
Code/Review Stylesheet

### ISSUE THREAD

**Issue by Clarice-COD** [Kitkatisvibing/look-and-feel-styleguide#12]
Fijn dat jullie gebruik maken van comments. Jullie hebben 2x een body in de css code. Zet dit samen in 1 body en een body hoort zo ver mogelijk boven.

Bij alle typografie elementen hebben jullie een class gemaakt, terwijl dat niet gebruikelijk is. Het is alleen maar meer werk en meer code. Zie voorbeeld hieronder:

`.h1{}`

moet worden:

`h1{}`

De variables zijn goed en duidelijk benoemd. Jullie hebben classes toegevoegd in de html maar geen naam gegeven. Laat deze eruit. 

Goed dat jullie de buttons een hover hebben gegeven en een begin van een formulier hebben gemaakt. Het formulier kan nog wel verder gestyled worden. De custome proporties zijn goed verwerkt in de body. 

@ambersr @kimnikitaschijf @OFRqq

**Comment by Ravirkt** [comment]
bedankt voor de feedback.

De feedback hebben we verwerkt in de files.
