### ISSUE TITLE
Feedback op Code

### ISSUE THREAD

**Issue by AnoukdeRooij24** [Kitkatisvibing/look-and-feel-styleguide#3]
- Duidelijke structuur aangehouden in de stylesheet
- Naamgeving van de custom properties zijn heel duidelijk en makkelijk te volgen
- Goed volledig gemaakt! (met hover en error!)
- De custom properties staan in de body. Dit ziet eruit als een bewuste keuze!
- Er is herhaling van code, maar niet in het zelfde bestand

- [ ] De body met alle custom properties staan in twee css bestandjes, dit is onlogisch en kan beter samengevoegd worden naar 1 bestand. Wij zouden het boven aan het bestand tumimundo.css zetten

@miel775 @Anouarab2

**Comment by Ravirkt** [comment]
bedankt voor de feedback

we hebben de feedback geimplementeerd
