### ISSUE TITLE
dry code 

### ISSUE THREAD

**Issue by Yu-Jing-van-Gerwen** [Kitkatisvibing/look-and-feel-styleguide#5]
je code is overzichtelijk en hier heb je 2x alles dubbel op de height na 

https://github.com/Kitkatisvibing/look-and-feel-styleguide/blob/efa174ebce98a3bc4040b2be886495bc60e18c5b/tumimundo.css#L147-L168

**Comment by Ravirkt** [comment]
bedankt voor je feedback!

Ik heb de feedback verwerkt.

groetjes, tumi mundo
