### ISSUE TITLE
Indeling stylesheet

### ISSUE THREAD

**Issue by saschavanvliet** [Kitkatisvibing/look-and-feel-styleguide#6]
De body staat bij jullie niet bovenaan. Dit is wel de bedoeling. Daarnaast hebben jullie twee body's gebruikt en dit moet er maar een zijn. 

Succes met het aanpassen! Groetjes, Team Drop&Heal.

**Comment by Ravirkt** [comment]
bedankt voor de feedback

We hebben de feedback geimplementeerd
