### ISSUE TITLE
de custom proporties kunnen bovenaan staan

### ISSUE THREAD

**Issue by Yu-Jing-van-Gerwen** [Kitkatisvibing/look-and-feel-styleguide#7]
ik zou de custom proporties boven aan op je pagina zetten waardoor het overzichtelijker is 

https://github.com/Kitkatisvibing/look-and-feel-styleguide/blob/efa174ebce98a3bc4040b2be886495bc60e18c5b/tumimundo.css#L206-L321

je kan ervoor kiezen om de custom proporties in de root te zetten waardoor die 1 hoger is in de specifity en dus hetzelfde is als de html 
je kan er meer over lezen in de documentatie

https://developer.mozilla.org/en-US/docs/Web/CSS/:root

https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties

**Comment by nadiachaja** [comment]
de body is naar boven verplaats
https://github.com/Kitkatisvibing/look-and-feel-styleguide/blob/main/tumimundo.css#L4-L130
